### ISSUE TITLE
리펙토링 방향성을 제안합니다!!

### ISSUE THREAD

**Issue by Lee-JongSoo** [Cocktail-Shop/backend#29]
현재 애플리케이션은 인터페이스 의존을 하고있지 않은 구조로 보입니다.
따라서 스프링 핵심가치인 IoC를 적극 활용하지 못하고 있는거 같습니다.

이에 전체적으로 리팩토링 해야할 필요가 있다고 생각했습니다!
설명을 위해 image 첨부합니다.
<img width="306" alt="스크린샷 2022-08-08 오전 3 07 26" src="https://user-images.githubusercontent.com/81428357/183304913-eaf31ef8-9a2e-4630-9a77-c21bdb0bb3d8.png">
<img width="683" alt="스크린샷 2022-08-08 오전 3 07 42" src="https://user-images.githubusercontent.com/81428357/183304928-6f4b6a07-7bd0-4596-bbd6-f506105b384e.png">
<img width="474" alt="스크린샷 2022-08-08 오전 3 10 05" src="https://user-images.githubusercontent.com/81428357/183304996-16de91b7-32f3-4310-ba5c-e710bd5f286f.png">

참고 문서: [https://mangkyu.tistory.com/194#:~:text=SOLID%EB%9E%80%20%EA%B0%9D%EC%B2%B4%20%EC%A7%80%ED%96%A5%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D,%EA%B8%80%EC%9E%90%EB%A5%BC%20%EB%94%B0%EC%84%9C%20%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A1%8C%EB%8B%A4](url)

0. 현재 각 레이어마다 추상화된 interface에 의존하고 있지 않고 구현체에 의존하고 있습니다.

1. 때문에 객체지향 5원칙 Solid를 준수하는 구조가 아닙니다.

2.이것이 왜 문제가 되는가하면 한 레이어에 로직을 수정하면 다른 레이어에도 영향을 미치게되므로, 관심사의 분리가 충분히 되지 않는다고 생각합니다.

3 결론. 추상화에 의존하는 방식으로 리팩토링 진행하는 것에 대한 의견을 남깁니다!!

<img width="665" alt="스크린샷 2022-08-08 오전 2 52 48" src="https://user-images.githubusercontent.com/81428357/183304399-63841250-c98d-4260-b1ff-7f5828c5ee70.png">

생각하시는 리펙토링 방향이나 이해가 안되시는 부분이 있으면 comment 남겨주세요!!!

**Comment by chae001122** [comment]
음 글로만 봤을 때는 어떻게 바꿔야 하는지 이해가 잘 되지 않네요ㅠㅠ 내일 코드 리뷰 후에 회의하면서 말해보도록 하면 좋을거 같습니다.

**Comment by geonjunk** [comment]
자료 감사합니다. interface를 두어 구현체가 인터페이스에 의존하도록 하는 패턴이라고 이해했습니다. 저도 쭉 공부해보고 낼 회의하면서 말해보면 좋을 것 같습니다!

**Comment by geonjunk** [comment]
8/15 적용 완료했습니다

**Comment by chae001122** [comment]
저도 제 파트에 적용 완료했습니다~
