### ISSUE TITLE
리팩토링 제안합니다 - 정적 팩토리 메서드

### ISSUE THREAD

**Issue by geonjunk** [Cocktail-Shop/backend#36]
## 제안하는 방식 - 정적 팩토리 패턴

- Effective java라는 도서에서는 생성자 대신 정적 팩토리 메서드를 통해 객체를 생성하는 패턴을 제안합니다.
- Entity나 DTO에서 생성자 대신 정적 메서드인 toEntity, toDTO 메서드를 통해 생성하는 방식입니다.
- 기본생성자는 직접 호출하지 않고 모두
 메서드를 통해 생성합니다.
- 장점은
    - 이름을 가질 수 있다
    - 호출할 때마다 새로운 객체를 생성할 필요가없다
    - 하위 자료형 객체를 반환할 수 있다
    - **객체 생성을 캡슐화 할 수 있다**
- 책에서 제시하는 장점은 참고자료에 설명이 되어있어 첨부하겠습니다.
    - [https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)

## 제안 사항1

- 저희가 현재 모델에서  toEntity, toDTO 메서드들은 구현하고 있는 방식과 유사합니다.
- 하지만 현재는 정적 메서드로 구현하지 않았습니다.
- 따라서,  toEntity, toDTO 메서드를 정적 메서드로 구현하는 방식을 제안합니다.
- 코틀린에서는 정적 메서드를 companion object를 통해 구현할 수 있습니다.
- 예시 코드입니다.
    
    ```kotlin
    data class ResponseIdInquiryDTO(val status:Int,val message:String,val result: IdInquiryResultDTO){
        companion object{
            fun memberToResponseIdInquiryDTO(status:Int,message:String,id:String): ResponseIdInquiryDTO {
                    return ResponseIdInquiryDTO(
                        status,
                        message,
                        IdInquiryResultDTO(id)
                    )
            }
        }
    }
    ```
    
    - member→DTO로 변환하는 메서드를 정적메서드로 구현했습니다.
- 이 후 호출시에는 아래와 같이 호출합니다.
    - 객체 생성을 캡슐화하기위해 전체 Member 객체를 넘깁니다. 

    
    ```kotlin
    return AuthMemberDTO.memberToAuthMemberDTO(member)
    ```
    

## 제안 사항2

- 정적 메서드를 적용한다면 to대신 from으로 메서드명을 바꾸는것도 좋을 것 같습니다.
- 위를 예시로 들면
    - AuthMemberDTO.memberToAuthMemberDTO()를
    - AuthMemberDTO.fromMember()로 변경합니다.
- 정적메서드라 AuthMemberDTO. 형식으로 호출되기때문에 앞에 한단어를 줄이고 좀 더 가독성 좋은 메서드 명이 될 수 있을 것 같습니다.

### 참고 자료

- 정적 팩토리 패턴
    - [https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)
- 코틀린에서 정적 메서드
    - [[코틀린, 코틀린답게 사용하기 - 3. Class (tistory.com)](https://jjeda.tistory.com/m/24)](https://jjeda.tistory.com/m/24)

**Comment by Lee-JongSoo** [comment]
좋은 정보 감사합니다. 좀 더 공부하고 저희 프로젝트에 적용시키겠습니다~

**Comment by Lee-JongSoo** [comment]
제 파트 정적 펙토리 패턴으로 리펙토링 완료하였습니다~!

**Comment by chae001122** [comment]
제 파트도 적용 완료하였습니다~
